"""wexin-update

Revision ID: 2a31b70ef223
Revises: 4793e05ee81d
Create Date: 2016-08-11 03:24:16.544093

"""

# revision identifiers, used by Alembic.
revision = '2a31b70ef223'
down_revision = '4793e05ee81d'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
