"""wexin_msg_add_field

Revision ID: 2b135ef4e4dc
Revises: 2a31b70ef223
Create Date: 2016-08-11 03:58:58.544917

"""

# revision identifiers, used by Alembic.
revision = '2b135ef4e4dc'
down_revision = '2a31b70ef223'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
