"""wexin migration

Revision ID: 4793e05ee81d
Revises: 4cefae1354ee
Create Date: 2016-08-11 02:50:25.852540

"""

# revision identifiers, used by Alembic.
revision = '4793e05ee81d'
down_revision = '4cefae1354ee'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('wechat_users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('wechat_id', sa.String(length=64), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('last_visit', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_wechat_users_last_visit', 'wechat_users', ['last_visit'], unique=False)
    op.create_index('ix_wechat_users_timestamp', 'wechat_users', ['timestamp'], unique=False)
    op.create_table('wechat_msgs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('msg_id', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('wechat_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['wechat_id'], ['wechat_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_wechat_msgs_timestamp', 'wechat_msgs', ['timestamp'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_wechat_msgs_timestamp', 'wechat_msgs')
    op.drop_table('wechat_msgs')
    op.drop_index('ix_wechat_users_timestamp', 'wechat_users')
    op.drop_index('ix_wechat_users_last_visit', 'wechat_users')
    op.drop_table('wechat_users')
    ### end Alembic commands ###
